services:
  artemis:
    image: apache/activemq-artemis
    ports:
      - "8161:8161"   # Web Console
      - "61616:61616" # AMQP
      - "5672:5672"   # MQTT

  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - "3000:80"
      - "2525:25"
