
  version: '3'
  services:
    minio:
      image: quay.io/minio/minio
      ports:
        - "9000:9000"
        - "9001:9001"
      volumes:
        - ./dev/minio/data/:/data
      environment:
        MINIO_ROOT_USER: admin123456
        MINIO_ROOT_PASSWORD: admin123456
      command: server /data --console-address ":9001"


